---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-managed-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
spec:
  containers:
    - name: mysqldb
      image: mysql:8
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: mysql-db
        - name: MYSQL_USER
          value: bv
        - name: MYSQL_PASSWORD
          value: P@ssw0rd
      volumeMounts:
        - name: dbvol
          mountPath: /var/lib/mysql
  volumes:
    - name: dbvol
      persistentVolumeClaim:
        claimName: aws-managed-disk
