---
apiVersion: v1
kind: Service
metadata:
  name: openmrs-svc
  labels:
    svc: lb
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: openmrs
    version: "1.0"
  type: LoadBalancer
