---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs-deploy
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: openmrscore
      ver: 2.4.0
  strategy:
    rollingUpdate:
      maxSurge: 35%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openmrscore
        ver: 2.4.0
    spec:
      containers:
        - name: openmrscore
          image: openmrs/openmrs:dev
          ports:
            - containerPort: 8080
              protocol: TCP